# Generated by Django 4.2.2 on 2023-06-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='Linenos',
        ),
        migrations.AddField(
            model_name='snippet',
            name='linenos',
            field=models.BooleanField(default=False),
        ),
    ]
